### ISSUE TITLE
Accepting compiled YARA rules

### ISSUE THREAD

**Issue by ctmayhew** [CrowdStrike/xwf-yara-scanner#2]
Add ability to accept compiled YARA rules as per [documentation](https://yara.readthedocs.io/en/stable/capi.html#c.yr_rules_load)

**Comment by ctmayhew** [comment]
This will be in version 1.2 😃

**Comment by rpsirois** [comment]
Please include support for `.yar` or `.yara` files which are _not_ precompiled or at least document this.

https://github.com/CrowdStrike/xwf-yara-scanner/blob/main/src/Yara.cpp#L284 should probably check the magic number header instead of only file extension and logically compile based on the absence of that (https://github.com/VirusTotal/yara/blob/master/libyara/arena.c#L550).

**Comment by ctmayhew** [comment]
I believe YARA does it's own magic number checking to see if the rule file is valid. If you would like to use rules which are not pre-compiled - just use a .txt extension.
